//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrepareDemo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<System.DateTime> OrderDeliveryDate { get; set; }
        public Nullable<int> OrderPickupPoint { get; set; }
        public Nullable<System.DateTime> OrderReservedDate { get; set; }
        public Nullable<int> OrderCode { get; set; }
        public Nullable<int> OrderClient { get; set; }
    
        public virtual User User { get; set; }
        public virtual PickupPoint PickupPoint { get; set; }
    }
}
