//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrepareDemo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string ProductArticleNumber { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public string ProductCategory { get; set; }
        public byte[] ProductPhoto { get; set; }
        public string ProductManufacturer { get; set; }
        public Nullable<decimal> ProductCost { get; set; }
        public Nullable<byte> ProductDiscountAmount { get; set; }
        public Nullable<int> ProductQuantityInStock { get; set; }
        public string ProductDiller { get; set; }
        public string Quantity { get; set; }
        public Nullable<byte> ProductMaxDiscountAmount { get; set; }
    }
}
